spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: username
    password: password
    driverClassName: org.h2.Driver

    # HikariCP settings
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPool
  jpa:
    # open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        #to show sql
        show_sql: false
        format_sql: true
        type:
          descriptor:
            sql: trace
        temp:
          use_jdbc_metadata_defaults: false
